
Vagrant.configure("2") do |config|
     config.vm.box = "geerlingguy/centos7"
     config.vm.network "private_network", ip: "192.168.33.15"
     config.vm.network "public_network"
     config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
     end
     config.vm.provision "shell", inline: <<-SHELL
       yum install httpd wget unzip -y
       systemctl start httpd
       systemctl enable httpd
       cd /tmp/
       wget https://www.tooplate.com/zip-templates/2108_dashboard.zip
       unzip -o 2108_dashboard.zip
       cp -r 2108_dashboard/* /var/www/html/
       systemctl restart httpd
     SHELL
  end
  