#to access wordpress we have to access through link : http://192.168.33.16/blog/
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
   config.vm.network "private_network", ip: "192.168.33.16"
  config.vm.network "public_network"
   config.vm.provision "shell", inline: <<-SHELL
   sudo apt update
   sudo apt install wordpress php libapache2-mod-php mysql-server php-mysql -y

   cp /vagrant/wordpress.conf /etc/apache2/sites-available/wordpress.conf

   sudo a2ensite wordpress
   sudo a2enmod rewrite
   sudo service apache2 reload

   mysql -u root -e 'CREATE DATABASE wordpress;'
   mysql -u root -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost IDENTIFIED BY "admin123";'
   mysql -u root -e 'FLUSH PRIVILEGES;'

   cp /vagrant/config-localhost.php /etc/wordpress/config-192.168.33.16.php
   service mysql restart
   SHELL
end
